# Generated by Django 6.1 on 2026-08-22 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_student_date_of_birth_student_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent / Guardian')], default='admin', max_length=12)),
                ('profile_photo', models.FileField(blank=True, upload_to='profiles/users/')),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_profile', to='management.parentprofile')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_profile', to='management.student')),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_profile', to='management.teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=180)),
                ('author', models.CharField(max_length=120)),
                ('isbn', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cover_image', models.FileField(blank=True, upload_to='library/covers/')),
                ('reading_file', models.FileField(upload_to='library/books/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('created_by', 'title', 'author'), name='unique_library_book')],
            },
        ),
    ]
