# Generated by Django 6.1 on 2026-08-22 19:18

from django.db import migrations, models


def copy_existing_scores_to_final(apps, schema_editor):
    GradeRecord = apps.get_model('management', 'GradeRecord')
    for record in GradeRecord.objects.exclude(score__isnull=True):
        record.final_score = record.score
        record.save(update_fields=['final_score'])


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_announcement_loginactivity_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='graderecord',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='first_term_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='second_term_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='teacher_remark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='third_term_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional individual assessment score (0 to 100).', max_digits=5, null=True),
        ),
        migrations.RunPython(copy_existing_scores_to_final, migrations.RunPython.noop),
    ]
