from django.urls import path
from . import views

urlpatterns = [
    path('sign-in/', views.sign_in, name='sign_in'),
    path('create-account/', views.create_account, name='create_account'),
    path('sign-out/', views.sign_out, name='sign_out'),
    path('change-password/', views.change_password, name='change_password'),
    path('my-profile/', views.my_profile, name='my_profile'),
    path('notifications/', views.notifications, name='notifications'),
    path('search/', views.search, name='search'),
    path('academic-year/select/', views.set_academic_year, name='set_academic_year'),
    path('announcements/', views.announcements, name='announcements'),
    path('parents/', views.parents, name='parents'),
    path('parents/<int:parent_id>/', views.parent_details, name='parent_details'),
    path('messages/', views.messages_page, name='messages'),
    path('timetable/', views.timetable, name='timetable'),
    path('transport/', views.transport, name='transport'),
    path('library/', views.library, name='library'),
    path('library/<int:book_id>/read/', views.read_book, name='read_book'),
    path('hr-payroll/', views.hr_payroll, name='hr_payroll'),
    path('system-settings/', views.system_settings, name='system_settings'),
    path('reports/', views.reports, name='reports'),
    path('', views.index, name='index'),
    path('academic-years/', views.academic_years, name='academic_years'),
    path('classes/', views.classes, name='classes'),
    path('teachers/', views.teachers, name='teachers'),
    path('teachers/<int:teacher_id>/', views.teacher_details, name='teacher_details'),
    path('teachers/<int:teacher_id>/photo/', views.update_teacher_photo, name='update_teacher_photo'),
    path('students/', views.students, name='students'),
    path('students/<int:student_id>/', views.student_details, name='student_details'),
    path('students/<int:student_id>/photo/', views.update_student_photo, name='update_student_photo'),
    path('subjects/', views.subjects, name='subjects'),
    path('attendance/', views.attendance, name='attendance'),
    path('exams-results/', views.exams_results, name='exams_results'),
    path('results/', views.results, name='results'),
    path('assignments/', views.assignments, name='assignments'),
    path('fees/', views.fees, name='fees'),
    path('financial-management/', views.financial_management, name='financial_management'),
]
